import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import NavList from './components/NavList';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
        bg-black-950 bg-gradient-to-r  from-gray-950 via-gray-800 to-transparent
        w-full flex h-full
        `}
      >
        <NavList />
        <main className="flex-1 min-h-screen overflow-y-auto p-4 sm:p-8 md:p-12">
          {children}
        </main>
      </body>
    </html>
  );
}
